import { PrismaClient } from '@prisma/client';
export { seedAuthors } from './authors';
export { seedCategories } from './categories';
export { seedCustomers } from './customers';
export { seedProducts } from './products';
export { seedConfigs } from './config';
export { seedFeedbacks } from './feedbacks';
export { seedOrders } from './orders';
export const prisma = new PrismaClient();
