# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: ['master', 'main', 'dev']
  pull_request:
    branches: ['master', 'main', 'dev']

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allow the workflow to be re-used in other workflows
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: API/Generate ZenStack Enhance
        run: pnpm run --filter=api zenstack generate
      - name: API/Generate Prisma Client
        run: pnpm run --filter=api prisma generate
      - name: Test API with Jest
        run: pnpm --filter=api run test
